---
title: "R y Python"
author: "Roger Ruiz i Andrés"
date: "29/4/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Reticulate

```{r}
library(reticulate)
use_python("/Users/rogerruiziandres/opt/anaconda3/bin/python3", required = TRUE)
py_config()
os <- import("os")
os$listdir(".")
```

```{r}
source_python("script_python.py")
add(3,4)
```

```{r}
math <- import("math")
math$pi
```

```{r}
np <- import("numpy", convert = FALSE)

x <- np$array(c(1:4))

sum <- x$cumsum()

print(sum)

py_to_r(sum)
class(sum)
```

```{r}
np <- import("numpy", convert = TRUE)

x <- np$array(c(1:4))

sum <- r_to_py(x)$cumsum()

print(sum)
```

```{r}
edad <- 33
edad_py <- r_to_py(edad)
```


```{python}
a = 3
print(a)
def suma(x,y):
  return x - y

suma(r.edad_py, 6)
```


```{r}
datos <- iris
head(datos)
datos_py <- r_to_py(datos)
```

```{python}
import pandas as np

r.datos_py.head()
```

```{r}
scan("../../scan_text.txt", sep = ";")
```

```{python}
import matplotlib.pyplot as plt
import numpy as np
```

```{python}
def f(x):
    return np.exp(-x)*np.cos(2*np.pi*x)
```

```{python}
x1 = np.arange(0, 5.0, 0.1)
x2 = np.arange(0, 5.0, 0.2)
```

```{python, fig.cap = "Hola"}
plt.figure(1)

plt.subplot(2,1,1)
plt.plot(x1, f(x1), 'ro', x2, f(x2), 'k')

plt.subplot(2,1,2)
plt.plot(x2, f(x2), 'g--')

plt.show()
```

