---
title: "Ejemplo_Completo_R"
author: "Roger Ruiz i Andrés"
date: '`r format(Sys.Date(),"%e de %B, %Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Ejemplo Completo

## Juntar color de ojos y pelo sin distinguir por sexo

```{r}
HairEyeColor
```


```{r}
male   <- HairEyeColor[, , 1]
female <- HairEyeColor[, , 2]
data   <- as.table(male + female)
data
```

## Manipulación de datos

```{r}
#Cambio de nombres d euna lista
dimnames(data) <- list(
  Pelo = c("Negro", "Marron", "Pelirrojo", "Rubio"),
  Ojos = c("Marrones", "Azules", "Pardos", "Verdes")
)
data
```

## Diagrama de mosaico

```{r}
plot(data, col = "lightblue", main = "Diagrama de Mosaico")
```

## Número total de individuos del dataframe

```{r}
sum(data)
```

## Tablas de frecuencias absolutas y relativas de cada variable

```{r}
colSums(data)
rowSums(data)
prop.table(colSums(data))
prop.table(rowSums(data))
```

## Diagrama de barras de las frecuencias anteriores

```{r}
barplot(prop.table(colSums(data)), col = c("burlywood4", "lightblue", "orange3", "lightgreen"), ylim = c(0, 0.4),
        main = "Frecuencias relativas para los colores de los ojos")
```

## Frecuencias relativas globales y marginales

```{r}
round(prop.table(data), 3)#Global
round(prop.table(data, margin = 1), 3)#Marginal por fila (Pelo)
round(prop.table(data, margin = 2), 3)#Marginal por columna (Ojos)
```

```{r}
library(gmodels)
CrossTable(data, prop.chisq = FALSE)
```


## Barplot de frecuencias marginales

```{r}
barplot(prop.table(data, margin = 1), beside = TRUE, legend.text = TRUE, ylim = c(0, 0.8),
        col = c("Black", "burlywood4", "Red", "Gold"),
        main = "Frecuencias relativas de cada color de pelo\n
        para cada color de ojos")
```

```{r}
barplot(t(prop.table(data, margin = 2)), beside = TRUE, legend.text = TRUE, ylim = c(0, 0.6),
        col = c("burlywood4", "lightblue", "orange4", "lightgreen"),
        main = "Frecuencias relativas de cada color de ojo\n
        para cada color de pelo")
```



